### PR TITLE
The Legend of Zelda - Majoras Mask 3D (USA) Added cheats for v1.1

### PR DESCRIPTION
**Pull request by tstambaugh92**
[boot.zip](https://github.com/JourneyOver/CTRPF-AR-CHEAT-CODES/files/2266080/boot.zip)
[boot.zip](https://github.com/JourneyOver/CTRPF-AR-CHEAT-CODES/files/2266082/boot.zip)

## Description
Many of the useful cheats from this file were 1.0 only. Updated these for 1.1 as well as added a few additional ones such as having the Oni Link mask on the B button(allows it to be used anywhere).

The cheats that cause rupees/items to be maxed out in quantity have been given a button press of A to activate. The reasoning being that the current Luma cheat engine only runs these codes once otherwise, which prevents them from being actually unlimited. Since A is a commonly used button in game, this keeps the quantities updated without having to re-open the cheat menu. Hopefully Luma updates to fix this hack.

## Types of changes

- [x ] Cheat fix
- [x ] New cheats
- [ ] Regional fix / Addition
- [ ] Other

## Additional Notes
The moon jump code is broken in the current cheat engine of Luma. I have a pull request for a fix in Luma that lets the code work. If its not working for you, its not you or the code at the moment, its just Luma. Code should work out of the box on a gateway or if converted to an NTR plugin.

### CODE REVIEW

**Comment by JourneyOver** [comment]
Thanks for this :) 

> The moon jump code is broken in the current cheat engine of Luma. I have a pull request for a fix in Luma that lets the code work. If its not working for you, its not you or the code at the moment, its just Luma. Code should work out of the box on a gateway or if converted to an NTR plugin.

Huh now I wonder how many codes I have removed over the past few months or so for being broken, that might not of been broken at all..

**Comment by JourneyOver** [comment]
@tstambaugh92 do you think if possible you could shoot me the boot.firm with the fix in place? just attach the file or something to this PR and I'll grab it when I can.

**Comment by tstambaugh92** [comment]
I attached it in a zip twice by accident, can't figure out how to remove it but both zips are the same.

This machine had zero dev tools on it installed last night and was a pain in the rear to do so I hope it helps out.

**Comment by JourneyOver** [comment]
That's fine :p and hehe yea it's one of the reasons why I just asked you to pass along the boot.firm so I wouldn't have to worry about trying to set up the dev tools and all that shit xD but thanks a bunch ^^

**Pull request merged**
