### PR TITLE
Update 00040000001AA900.txt

### PR DESCRIPTION
**Pull request by jmapjp**
## Types of changes

- [ ] Cheat fix
- [x] New cheats
- [ ] Regional fix / Addition
- [ ] Other

### CODE REVIEW

**Comment by JourneyOver** [comment]
Hey @jmapjp are you planning on adding more cheats/update codes for anything else at the moment? I can keep this open for a bit longer so you don't have to keep on making branches and can just push everything you do into this pull request for the time being xD

**Comment by JourneyOver** [comment]
going to go ahead and merge this I guess >.<

**Comment by jmapjp** [comment]
Not for a bit, that was the last bit I wanted to put in

**Comment by jmapjp** [comment]
for now that is

**Comment by JourneyOver** [comment]
Okay haha :p

**Pull request merged**
