### PR TITLE
Code update [MHST (US), PCV (VC), Majoras Mask (US)]

### PR DESCRIPTION
**Pull request by iSharingan**
## Description
Overhaul of several MHStories (US) codes for ease of use/to remove side effects. Added various battle, egg, and stat codes. Minor additions/fixes to other games (Pokemon Crystal, Majora's Mask)

## Types of changes

- [x] Cheat fix
- [x] New cheats
- [ ] Regional fix / Addition
- [ ] Other

## Additional Notes
Ignore the reverted reverts :stuck_out_tongue: Command line was being annoying on merging just your most recent DB update, so this was the next best thing.

### CODE REVIEW

**Comment by JourneyOver** [comment]
lol it's fine, usually when things like that happen and CLI fucks things up terribly I usually just say fuck it and remake the fork of whatever I was working on and then re-adding my changes back in again with the fresh fork xD

If you want to go that route I can close this PR and you can delete your current fork and then refork and open a new PR?

**Comment by iSharingan** [comment]
it should be fine now. after the merge I can just delete and re-fork. by reverting my changes, merging your update to my fork, then reverting my reversions I have everything updated so this PR will have no problems.

I just need to remember to check if you've updated anything and merge it before committing to my own fork in the future (at least to avoid the train-wreck of double reversions. This still technically works, after all - it just looks like crap)

**Comment by JourneyOver** [comment]
Another thing is can you make a PR to sharkive as well with your changes? I'm pretty busy today so I don't really have a whole lot of time to sit down and copy your changes over to sharkive and make the adjustments that need to be made (removing notes/folder setup stuff/all that kinda stuff we talked about before on the sharkive repo)

edit: Alright I'll go ahead and squash and merge then ^^

**Comment by iSharingan** [comment]
Eh, sure. also, minor error in the description for the egg 1 blue saddle code on MHST. Note should read as top left gene, not top right. I'll fix it in my next code dump if you don't get around to it (its not super important)

**Comment by JourneyOver** [comment]
Fixed it

**Pull request merged**
