### PR TITLE
Majoras Mask 3D (USA)

### PR DESCRIPTION
**Pull request by tstambaugh92**
[boot.zip](https://github.com/JourneyOver/CTRPF-AR-CHEAT-CODES/files/2271203/boot.zip)

## Description

This cheat used to move 4 bytes, when I made it one byte I forgot to change the address. Derp.

## Types of changes

- [ X] Cheat fix
- [ ] New cheats
- [ ] Regional fix / Addition
- [ ] Other

### CODE REVIEW

**Comment by JourneyOver** [comment]
So going by your last commits title for this PR, do you want me to merge this in? or wait until you can get a chance to test things?

**Comment by JourneyOver** [comment]
btw mind throwing up the boot.firm for this PR https://github.com/AuroraWright/Luma3DS/pull/1117 (if it's still running with your previous fix as well of course) always good to get the fixes for the cheat functionality early for when I need to tests on codes and such.

**Comment by tstambaugh92** [comment]
I'm at work but I'll throw it up around 5pm eastern US time.

 You can accept this change, my code was just flat wrong previously. I noticed it wasn't working for my son and then tested on a new file myself, not sure how I messed that up.

If my new changes get added to Luma I'll be resubmitting these majoras Mask codes without the A press to activate since they'll be acting as originally intended. Going to test other Zelda game codes this weekend and write any new codes I feel improve life

**Comment by tstambaugh92** [comment]
Oh wait, this seems to include that link between worlds commit. I'm new to git, that wasn't supposed to be included. But my change is still valid, offsets should be cleared after each code. My comment simply meant I haven't seen if the codes actually function on the latest update, but all I did in that commit was make each code clear it's offset when finished or working or not those lines should have been there in the first place.

**Comment by JourneyOver** [comment]
Sounds good :) and going to go ahead and merge this in then ^^

> I'm new to git, that wasn't supposed to be included.

Anything you end up pushing to master or whatever branch you use for creating a PR will end up being included in said PR if the PR doesn't get merged before hand, doesn't matter if you pushed it before or after the PR was created. Easy way to get around that is to use branches so like for example you could of used one branch to make the PR with the commit to fix the code, while using another branch to do other things that you can then send a PR from that branch at another time if you didn't want whatever you was doing to end up in the first PR.

**Comment by tstambaugh92** [comment]
Left early for the day so the boot is in the now included zip file for you. Enjoy infinite life! My kids are both enjoying the hell out of it.

**Comment by tstambaugh92** [comment]
Also I just realized that if I make more commits after a pull request they still show up in the pull request. I guess I should branch after a pull request until its been accepted? My last job used Git/SourceTree and I totally fucked up a days of work for the whole office with a bad pull request once, I should probably learn what I'm doing lol

Edit: And you explained it in a comment to me to. Getting notifications seems iffy on here right now for me

**Comment by JourneyOver** [comment]
thanks :) one thing I can request though is don't change the version number for luma when sending me the boot.firms as I have reports from some people that it breaks certain homebrew apps sadly since the version number in luma is set at 0.0

**Pull request merged**
