### PR TITLE
Codes made for the classic  kirby game of old

### PR DESCRIPTION
**Pull request by jmapjp**
made a folder too..i still don't know why i cant put any symbols though

### CODE REVIEW

**Comment by JourneyOver** [comment]
That's fine sadly I don't have a computer at the moment since mine decided to shit the bed and stopped working so I have no way to fix the folder name for now, but thankfully I don't need a computer to at least accept pull requests.

**Comment by jmapjp** [comment]
Why was the computer even on the bed lol jk.. cool..but how do you even fix
it? I feel like theres some programming involved..

**Comment by JourneyOver** [comment]
Oh you mean for the notes? Yea those won't show up on windows due to the fact that windows doesn't have the font to show it, things should show correctly on thr 3DS though.

I was talking more about just the folder name to replace some of the "-" bits, but it'll be a good while before I I'm able to do such a thing.

**Comment by jmapjp** [comment]
Oh i see... i meant replacing the "-" bits  though.

**Pull request merged**
