### PR TITLE
Update: Alliance Alive (USA)

### PR DESCRIPTION
**Pull request by Letrico**
## Description
Added new cheat codes

## Types of changes

- [ ] Cheat fix
- [x] New cheats
- [ ] Regional fix / Addition
- [ ] Other

### CODE REVIEW

**Comment by JourneyOver** [comment]
Thanks, I haven't really paid much attention (or really any attention) to the gateway cheats thread on GBATemp so I miss a lot of stuff xD

**Comment by Letrico** [comment]
Haha is cool. I was updating my files in 3ds and might as well just push it to the repo. There is one more cheat which is movement speed but it comes with a few options that is required to change one segment of the code for different speed and I'm not sure if I should put it in since people might just put the txt directly and failed the code.

Do you have any idea how to do it?

**Comment by JourneyOver** [comment]
I've actually already taken care of the speed cheat :p I just made options for each speed that was created.

**Comment by Letrico** [comment]
Hahaha I guess that works too :p

**Pull request merged**
